# Generated by Django 3.1.5 on 2021-05-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210504_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dimension',
            field=models.CharField(default='1920x1080', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='format',
            field=models.CharField(default='JPG', max_length=50),
        ),
    ]
